simsage/admin

public/settings.js
=> set version to 7.7.4

src/features/auth/authSlice.js, src/features/groups/groupSlice.js, src/features/knowledge_bases/knowledgeBaseSlice.js, src/features/organisations/organisationSlice.js, src/features/sources/sourceSlice.js, src/features/users/usersSlice.js
Remove the end / if there are not any parameters after that.
=> fix api urls

src/features/semantics/SemanticEdit.js
Hitting save with no values was allowed. 
I have updated the form to use react-hook-form to handle this better.
=> added semantic form validation

src/components/MainSection.js, src/features/organisations/OraganisationEdit.js, src/features/organisations/OrganisationHome.js
=> show add org form fixed

src/components/MainSection.js, src/features/organisations/OrganisationHome.js, src/features/users/UserEdit.js, src/features/users/UserEditV2.js, src/features/users/UsersHome.js
organisation editor pop-up works when clicking the settings icon
=> Ar 218 bug fix

src/features/inventory/inventorySlice.js
Temp fix for inventory pagination issue.
=> WIP solution for inventory count bug

src/components/MainSection.js, src/features/synsets/SynsetList.js, src/features/synsets/SynsetsHome.js
added synset page back and removed stray 'c'
=> added synset page back and removed stray 'c'

src/features/auth/authSlice.js, src/features/auth/pageLayout.jsx, src/features/home/Home.js, src/home.js
fixed for now using an ugly global variable...
needs more work - but I need it to work :)
=> fixed sign-in problem with admin UX

src/features/organisations/OrganisationHome.js
Tried replicating from the method used in the account-dropdown.js file
=> adding selected style to org list

src/features/inventory/InventoryHome.js
updating num_inventory_list_items parameter to use the totalCount variable instead of timeList.length
=> updating num_inventory_list_items bug

src/features/text_to_search/TextToSearchList.js, src/features/text_to_search/TextToSearchTest.js
Updating button and header names to be consistent with each other
=> test to search naming consistent

src/features/sources/forms/CrawlerWebForm.js
=> added js render switch

public/settings.js, src/features/groups/groupEdit.js
-Have updated the user list to pull all available users for the group.
-Have added a filter at the top to search the list for the desired user
=> All users are not displaying in group management

src/features/sources/forms/CrawlerWebForm.js
Updated the web crawler form to reflect the rest of the crawlers
=> replace svg with react icons

src/features/knowledge_bases/KnowledgeBaseList.js, src/includes/left-navbar.js
Updated the onClick in the knowledgebase list to update the knowledgebase select element value too. 
Also, added a little style change to make them pointer-cursor.
=> KB list click updates dropdown

src/features/bot/BotEdit.js, src/features/bot/BotList.js, src/features/bot/BotSuccessMessage.js, src/features/bot/botSlice.js
-Added success message to improve user experience.
=> Add successful Bot item add message

src/features/sources/SourceEdit.js, src/features/sources/SourceErrorDialog.js, src/features/sources/SourceTest.js, src/features/sources/sourceSlice.js
Have updated the error handling to use rejectWithValue to pass the response to the rejected case.
=> implement rejectWithValue solution

src/features/sources/SourceForm.js, src/features/sources/forms/GeneralForm.js
Updating the source form logic, to allow certain toggles to appear for particular sources when drop down is updated.
=> crawler specific toggles

src/features/organisations/OrganisationHome.js, src/includes/account-dropdown.js
The groups associated to a specific org were not displaying when editing the org.
=> missing groups on org edit bug

src/features/groups/GroupList.js
Adding error to display when you try to delete a group with users still assigned.
=> add group delete with users error

src/features/knowledge_bases/KnowledgeBaseList.js
Adding button to refresh KB list
=> adding kb list refresh

public/settings.js, src/features/knowledge_bases/KnowledgeBaseForm.js, src/features/knowledge_bases/KnowledgeBaseSecurityDialog.js, src/features/knowledge_bases/knowledgeBaseSlice.js
Adding in a prompt to warn user before refreshing security ID
=> refresh security id prompt

src/features/users/UserEditV2.js
Updated the useEffect to be triggered when roles are changed, and not just the  KBs
=> forced kb assigned bug fix

src/features/organisations/OrganisationFormV2.js
Updated it to be trigger by SSO enabled instead of org enabled
=> org domain required when sso enabled

src/features/organisations/OrganisationFormV2.js
Updated the use effect to check if the SSO enabled flag is check as opposed to the org enabled flag.
=> updated new org bug

src/features/categorization/CategorizationList.js, src/features/semantics/SemanticsList.js, src/features/synonyms/SynonymList.js, src/features/synsets/SynsetList.js
Adding in a button to refresh all the lists in the mind.
=> adding refresh buttons

src/features/categorization/CategorizationEdit.js
Updated the href in the a tag as wasn't resolving correctly.
=> updated pdf file path

src/features/users/UserEditV2.js
added a getGroupList dispatch to the useEffect in the user form.
=> get group list for new users
